### ISSUE TITLE
Documentation for canonicalName

### ISSUE THREAD

**Issue by JRice** [GlobalNamesArchitecture/gnparser#480]
https://github.com/GlobalNamesArchitecture/gnparser/blob/master/README.rst#getting-the-simplest-possible-canonical-form

...This references names that I am not seeing in the JSON response. Perhaps this is covered in #209 but I thought it would be lower-hanging fruit to just update those strings in the existing docs.

**Comment by dimus** [comment]
@JRice you probably did not see these names because in Go version of gnparser they are called `CanonicalName->simple` and `CanonicalName->full` in contrast with Scala parser. The reason for chaning was omitting hybrid signs in `simple` for named hybrids. Many times people omit hybrid sign for named hybrids, and we do want to match ``Iris germanica`` and ``Iris x germanica`` using `simple` canonical form. So `simple` form is for matching purposes, and `full` form is for presentation purposes.
We changed the name because `valueRanked` now includes named hybrids, and its semantic meaning drifted as a result.

**Comment by dimus** [comment]
Closing it here, as the ticket is related to https://gitlab.com/gogna/gnparser
